Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [7]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [24]:
x = np.ones([8,8])
x[1::2, ::2] = 0
x[::2, 1::2] = 0
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю(еще ниже код над диагональю). Остальные значения - нули


In [18]:
x = np.diag( np.arange(1, 5), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
x = np.diag( np.arange(1, 5),k = 1)
print(x)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [33]:
x = np.random.random((5,5))
for i in range (0,5):
    s = 0
    for j in range (0,5):
        s += x[i, j]
        x[i, j] = (5-j)/ 5 * x[i, j] - 1/5 * s 
print(x)

[[ 0.71709863  0.0652512   0.0525461  -0.28776025 -0.54713568]
 [ 0.5452371   0.43431837 -0.17936115 -0.31796514 -0.48222917]
 [ 0.0893367   0.06012602  0.33337405 -0.04371141 -0.43912536]
 [ 0.26059065  0.08967448  0.01220837 -0.15442431 -0.20804919]
 [ 0.0481213   0.03975259  0.21624754 -0.14898926 -0.15513216]]


Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [41]:
x = np.random.sample((10,3))
for i in range (0, 10):
    minn = x[i,0]
    for j in range (0, 3):
        if(abs(minn-0.5) > abs(x[i,j]-0.5)):
            minn = x[i,j]
    print(minn) 
print(x)

0.25218090254437087
0.16326071772144868
0.45802679395072343
0.5497805877071609
0.31955413511266395
0.8327911117766039
0.3520938448133827
0.7589357035621035
0.6215360583785703
0.5200335944967728
[[0.2521809  0.85268952 0.86244106]
 [0.16326072 0.95184524 0.98900549]
 [0.45802679 0.6415344  0.71290013]
 [0.66818098 0.66281696 0.54978059]
 [0.31955414 0.13788704 0.01524124]
 [0.97944901 0.91414435 0.83279111]
 [0.35209384 0.27754011 0.20535316]
 [0.7589357  0.88986293 0.18834212]
 [0.62153606 0.04032694 0.81149245]
 [0.54571974 0.52003359 0.36183206]]


In [42]:
#еще один вариант с другой записью вывода
x = np.random.sample((10,3))
minstring = [ ]
for i in range (0, 10):
    minn = x[i,0]
    for j in range (0, 3):
        if(abs(minn - 0.5) > abs(x[i,j] - 0.5)):
            minn = x[i,j]
    minstring.append(minn)
print(minstring)       
print(x)

[0.20350832244003136, 0.38988579878146257, 0.7766434768726485, 0.5498637569709494, 0.6197025157181381, 0.44724857475386615, 0.6957701134074924, 0.7246989651627221, 0.47004773325390825, 0.503220197377304]
[[0.8294205  0.82290715 0.20350832]
 [0.66243545 0.62343434 0.3898858 ]
 [0.77664348 0.88561357 0.97849259]
 [0.54986376 0.61882088 0.32434166]
 [0.66368084 0.32938618 0.61970252]
 [0.31908579 0.30366167 0.44724857]
 [0.08732374 0.69577011 0.16640045]
 [0.25202776 0.72469897 0.83909054]
 [0.67292511 0.47004773 0.81554271]
 [0.7514209  0.55535958 0.5032202 ]]


Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [48]:
x = np.random.random((6,6))
for i in range(6):
    print(sum(x[i]) / max((x[j][i] for j in range(0,6))))
print(x)

2.367676582712405
4.65500112085187
2.8356749935755454
2.9599344629139375
3.9610890486762824
4.539970813588743
[[0.13056674 0.12120999 0.53940372 0.20327933 0.57269079 0.63629652]
 [0.22651311 0.89652567 0.89068284 0.53311236 0.95576503 0.86959524]
 [0.79015653 0.55207995 0.01956367 0.3399763  0.54517715 0.27873345]
 [0.03845011 0.13758989 0.82864281 0.46951834 0.91595079 0.18168004]
 [0.93063685 0.93924666 0.84244287 0.50861418 0.28410262 0.28082721]
 [0.66046163 0.2006487  0.65976955 0.86888139 0.86983225 0.92079672]]


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [51]:
x =  [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max((x[i] for i in range(1, len(x)) if x[i - 1] == 0)))

5


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [55]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j] += 1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.

In [57]:
T = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
D = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1]) / 4 for t in np.lib.stride_tricks.sliding_window_view(T, (2, 2) ) for b in t]).reshape(len(T[0: , 0]) - 1, len(T[0, 0:]) - 1)
print(D) 

[[ 5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
 [15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5]
 [25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5]]
