Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.
(было без цикла, поэтому без исправлений)


In [2]:
import numpy as np
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.
(было без цикла, поэтому без исправлений)

In [3]:
x = np.ones([8,8])
x[1::2, ::2] = 0
x[::2, 1::2] = 0
print(x)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю(еще ниже код над диагональю). Остальные значения - нули. (тоже было без цикла)

In [4]:
x = np.diag( np.arange(1, 5), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.(исправлено)

In [5]:
x = np.random.random((5,5))
nx = x - np.mean(x, axis =1, keepdims = True)
print(nx)

[[ 0.34965945 -0.33482657  0.35500171  0.04634647 -0.41618106]
 [-0.32761756 -0.17585575  0.10441515  0.23484937  0.1642088 ]
 [ 0.15546148 -0.05914931  0.01003634 -0.09491604 -0.01143247]
 [ 0.04746533  0.11642059 -0.40128612 -0.22179224  0.45919245]
 [-0.12069709 -0.21163264  0.36128802 -0.1916465   0.16268822]]


Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.(исправлено)

In [6]:
x = np.random.sample((10,3))
print(x)
print ([x[i ,np.argmin(abs(x - 0.5), axis = 1)[i]] for i in range(x.shape[0])])

[[0.50318769 0.32091776 0.12097704]
 [0.17068921 0.7082543  0.98793763]
 [0.2756938  0.53961619 0.39189112]
 [0.25142351 0.64694273 0.23071563]
 [0.76204347 0.27900909 0.19301854]
 [0.52930166 0.26761984 0.63028134]
 [0.08927916 0.50006888 0.79014089]
 [0.62626992 0.44996749 0.32107441]
 [0.45774358 0.4820109  0.69965741]
 [0.06429184 0.5136118  0.02283633]]
[0.5031876928453692, 0.70825430156703, 0.5396161926970476, 0.6469427250524932, 0.27900908967257, 0.5293016611825001, 0.5000688755112044, 0.4499674868955401, 0.4820109004067553, 0.5136118033407757]


Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.
(исправлено)

In [8]:
x = np.random.random((6, 6))
print(x)

print(np.sum(x, axis = 1)/ np.max(x, axis = 0))

[[0.03436058 0.28742416 0.49782548 0.18865884 0.0491769  0.23547356]
 [0.63305965 0.77385639 0.59050653 0.85940014 0.35916431 0.61676819]
 [0.58183571 0.33539863 0.56640174 0.85855771 0.87443232 0.63806703]
 [0.35251882 0.81539986 0.58400313 0.5036372  0.59561139 0.85271959]
 [0.39387951 0.62501831 0.24334274 0.40842315 0.94241716 0.44460232]
 [0.42691658 0.94155066 0.6269436  0.83277483 0.94863315 0.33127628]]
[2.04233442 4.070684   6.14838904 4.30985501 3.22325146 4.81763892]


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.(как было)

In [9]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max((x[i] for i in range(1, len(x)) if x[i - 1] == 0)))

5


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.(исправлено)

In [17]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength = len(x))
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.(как было)

In [17]:
T = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
D = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1]) / 4 for t in np.lib.stride_tricks.sliding_window_view(T, (2, 2) ) for b in t]).reshape(len(T[0: , 0]) - 1, len(T[0, 0:]) - 1)
print(D)

[[ 5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
 [15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5]
 [25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5]]
